const ENV = {
	COINGECKO_API_KEY: import.meta.env.VITE_BASE_CRYPTO_URL,
	BASE_CRYPTO_URL: import.meta.env.VITE_BASE_URL,
}

export const API_KEY = ENV.COINGECKO_API_KEY
export const CRYPTO_URL = ENV.BASE_CRYPTO_URL
